# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'fript_mobile' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for fript_mobile
#  #
#
#  target 'fript_mobile-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'fript_mobileTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#end

#target 'fript_mobile-tvOS' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for fript_mobile-tvOS
#
#  target 'fript_mobile-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end

target 'fript_mobile' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'
end
